name: nsides
channels:
  - conda-forge
dependencies:
  - conda-forge::ipykernel=5.1.2
  - conda-forge::numpy=1.17.2
  - conda-forge::pandas=0.25.1
  - conda-forge::python=3.7.3
  - conda-forge::scikit-learn=0.21.3
  - conda-forge::scipy=1.3.1
  - conda-forge::tqdm=4.36.1

